services:
  mongo:
    image: mongo
    container_name: imatch-mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    env_file:
      - .env
    networks:
      - imatch-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongo}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-imatch}

  mongo-express:
    image: mongo-express
    container_name: imatch-mongo-express
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - ${ME_PORT:-8081}:8081
    networks:
      - imatch-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-mongo}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      ME_CONFIG_MONGODB_SERVER: imatch-mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME:-meadmin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD:-meadmin}

  redis:
    image: redis
    container_name: imatch-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - imatch-network

networks:
  imatch-network:
    driver: bridge
    name: imatch-network
